name: Build ruleset and geodata
on:
  workflow_dispatch:
  schedule:
    - cron: "0 19 * * *"
  push:
    branches:
      - master
    paths-ignore:
      - "**/README.md"

env:
  domains_download_url: https://raw.githubusercontent.com/dududuK/domain-list-custom/domains
  mihomo_ruleset_path: ./mihomo-ruleset
  tools_domains_path: ./tools/domains
  tools_rules_path: ./tools/rules
  mihomo_core_path: ./tools/mihomo
  domains: private ads microsoft-cn apple-cn google-cn games-cn ai netflix disney max primevideo appletv youtube tiktok bilibili tld-proxy proxy tld-cn cn proxylite
  archs: applications networktest

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set update_version variable
        run: |
          echo "update_version=$(date -d '+8 hours' '+%Y-%m-%d')" >> ${GITHUB_ENV}
        shell: bash

      - name: Checkout Repository
        uses: actions/checkout@master

      - name: Checkout dududuK/domain-list-custom
        uses: actions/checkout@v4
        with:
          repository: dududuK/domain-list-custom
          path: custom

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: ./custom/go.mod
          cache-dependency-path: ./custom/go.sum

      - name: Generate `mihomo` rule-set
        run: |
          mkdir -p "${{ env.mihomo_ruleset_path }}"

          # Function to download and process domain/arch lists
          generate_ruleset() {
            local type="$1" # yaml, text, mrs
            local format_flag=""
            # sed command to transform DOMAIN-SUFFIX entries for text and mrs formats
            # Example: DOMAIN-SUFFIX,example.com  ->  +.example.com
            local sed_domain_suffix_text='-e "s/^DOMAIN-SUFFIX,/+\./"'

            # sed command to remove DOMAIN-REGEX entries prefix for text and mrs formats
            # Example: DOMAIN-REGEX,^example\.com$  ->  ^example\.com$
            local sed_domain_regex_text='-e "s/^DOMAIN-REGEX,//"'

            # sed command to remove DOMAIN entries for text and mrs formats
            # Example: DOMAIN,example.com  ->  example.com
            local sed_domain_text='-e "s/^DOMAIN,//"'

            # sed command to transform DOMAIN-SUFFIX entries for yaml format
            # Example: DOMAIN-SUFFIX,example.com  ->   - '+.example.com'
            local sed_domain_suffix_yaml='-e "s/^DOMAIN-SUFFIX,/  - \'+\./"'

            # sed command to transform DOMAIN entries for yaml format
            # Example: DOMAIN,example.com  ->   - 'example.com'
            local sed_domain_yaml='-e "s/^DOMAIN,/  - \'/"'


            if [ "$type" = "yaml" ]; then
              format_flag="yaml"
              sed_domain_suffix="${sed_domain_suffix_yaml}"
              sed_domain="${sed_domain_yaml}"
              prefix='echo "payload:" >'
              suffix=".yaml"
              sed_content_domain='grep -E "DOMAIN,|DOMAIN-SUFFIX," | sed ${sed_domain} ${sed_domain_suffix} -e "s/\$/\'/"'
              sed_content_fakeip='sed ${sed_domain} ${sed_domain_suffix} ${sed_domain_regex_text} -e "s/\'\.\//\'/" -e "s/\$/\'/"'
              sed_content_arch='sed "s/^/  - /"'

            elif [ "$type" = "text" ]; then
              format_flag="text"
              sed_domain_suffix="${sed_domain_suffix_text}"
              sed_domain="${sed_domain_text}"
              prefix=''
              suffix=".list"
              sed_content_domain='grep -E "DOMAIN,|DOMAIN-SUFFIX," | sed ${sed_domain} ${sed_domain_suffix}'
              sed_content_fakeip='sed ${sed_domain} ${sed_domain_suffix} ${sed_domain_regex_text} -e "s/^\.//"'
              sed_content_arch='sed "s/^/  - /"'

            elif [ "$type" = "mrs" ]; then
              format_flag="mrs"
              sed_domain_suffix="${sed_domain_suffix_text}"
              sed_domain="${sed_domain_text}"
              prefix='mkdir -p "${{ env.tools_domains_path }}/$name/" && curl "$domains_download_url/$name.list" | grep -E "DOMAIN,|DOMAIN-SUFFIX," | sed ${sed_domain} ${sed_domain_suffix} >'
              suffix=".list"
              sed_content_domain='grep -E "DOMAIN,|DOMAIN-SUFFIX," | sed ${sed_domain} ${sed_domain_suffix}'
              sed_content_fakeip='sed ${sed_domain} ${sed_domain_suffix} ${sed_domain_regex_text} -e "s/^\.//"'
              sed_content_arch='sed "s/^/  - /"'
            fi


            # Generate rule-set for domains
            for name in ${{ env.domains }}; do
              if [ "$type" = "yaml" ] || [ "$type" = "text" ]; then
                ${prefix} "${{ env.mihomo_ruleset_path }}/${name}${suffix}"
                curl -sSL "${{ env.domains_download_url }}/${name}.list" | ${sed_content_domain} >> "${{ env.mihomo_ruleset_path }}/${name}${suffix}"
              elif [ "$type" = "mrs" ]; then
                ${prefix} "${{ env.tools_domains_path }}/$name/${name}${suffix}"
              fi
            done

            # Generate rule-set for fakeip-filter
            if [ "$type" = "yaml" ] || [ "$type" = "text" ]; then
              ${prefix} "${{ env.mihomo_ruleset_path }}/fakeip-filter${suffix}"
              curl -sSL "${{ env.domains_download_url }}/fakeip-filter.list" | ${sed_content_fakeip} >> "${{ env.mihomo_ruleset_path }}/fakeip-filter${suffix}"

              ${prefix} "${{ env.mihomo_ruleset_path }}/fakeip-filter-lite${suffix}"
              curl -sSL "${{ env.domains_download_url }}/fakeip-filter-lite.list" | ${sed_content_fakeip} >> "${{ env.mihomo_ruleset_path }}/fakeip-filter-lite${suffix}"
            elif [ "$type" = "mrs" ]; then
              mkdir -p "${{ env.tools_domains_path }}/fakeip-filter/"
              curl -sSL "${{ env.domains_download_url }}/fakeip-filter.list" | ${sed_content_fakeip} > "${{ env.tools_domains_path }}/fakeip-filter/fakeip-filter${suffix}"
              mkdir -p "${{ env.tools_domains_path }}/fakeip-filter-lite/"
              curl -sSL "${{ env.domains_download_url }}/fakeip-filter-lite.list" | ${sed_content_fakeip} > "${{ env.tools_domains_path }}/fakeip-filter-lite/fakeip-filter-lite${suffix}"
            fi


            # Generate rule-set for archs
            if [ "$type" = "yaml" ]; then
              mkdir -p "${{ env.mihomo_ruleset_path }}"
            elif [ "$type" = "text" ]; then
              mkdir -p "${{ env.mihomo_ruleset_path }}"
            elif [ "$type" = "mrs" ]; then
              mkdir -p "${{ env.tools_rules_path }}"
            fi

            for name in ${{ env.archs }}; do
              if [ "$type" = "yaml" ]; then
                ${prefix} "${{ env.mihomo_ruleset_path }}/${name}${suffix}"
                curl -sSL "${{ env.domains_download_url }}/${name}.list" | ${sed_content_arch} >> "${{ env.mihomo_ruleset_path }}/${name}${suffix}"
              elif [ "$type" = "text" ]; then
                curl -sSL "${{ env.domains_download_url }}/${name}.list" > "${{ env.mihomo_ruleset_path }}/${name}${suffix}"
              elif [ "$type" = "mrs" ]; then
                mkdir -p "${{ env.tools_rules_path }}/$name/"
                curl "${{ env.domains_download_url }}/${name}.list" > "${{ env.tools_rules_path }}/$name/${name}${suffix}"
              fi
            done
          }

          generate_ruleset "yaml"
          generate_ruleset "text"
          generate_ruleset "mrs"


      - name: Download and unzip `mihomo` core
        run: |
          mkdir -p "${{ env.tools_core_path }}"
          wget https://github.com/DustinWin/proxy-tools/releases/download/mihomo/mihomo-alpha-linux-amd64.tar.gz -O - | tar -zxf - -C "${{ env.tools_core_path }}"
          mv -f "${{ env.tools_core_path }}/CrashCore" "${{ env.tools_core_path }}/mihomo"

      - name: Generate `mihomo` rule-set (mrs) convert
        run: |
          cd "${{ env.tools_core_path }}" || exit 1
          chmod +x ./mihomo
          list=($(ls ${{ env.tools_domains_path }}))
          for item in "${list[@]}"; do
            ./mihomo convert-ruleset domain text "${{ env.tools_domains_path }}/$item/$item.list" "${{ env.mihomo_ruleset_path }}/$item.mrs"
          done

      - name: Release and upload `mihomo-ruleset` assets
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          release_name: mihomo-ruleset
          tag: mihomo-ruleset
          overwrite: true
          body: |
            [mihomo](https://github.com/MetaCubeX/mihomo) rule-set 规则集文件
            规则集文件更新于 ${{ env.update_version }}
          file_glob: true
          file: ${{ env.mihomo_ruleset_path }}/*

      - name: Commit and push `mihomo-ruleset` branch
        run: |
          cd "${{ env.mihomo_ruleset_path }}" || exit 1
          git init
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git checkout -b mihomo-ruleset
          git add . && git commit -m "mihomo rule-set 规则集文件更新于 ${{ env.update_version }}"
          git remote add origin "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}"
          git push -f origin mihomo-ruleset

      - name: Purge jsDelivr CDN
        run: |
          cd "${{ env.mihomo_ruleset_path }}" || exit 1
          for file in $(ls); do
            curl -i "https://purge.jsdelivr.net/gh/${{ github.repository }}@mihomo-ruleset/${file}"
          done

      - name: Delete old workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          retain_days: 3
          keep_minimum_runs: 1
